<?php


namespace App\Service;

use App\Repository\CallRepository;
use App\Repository\CityRepository;
use App\Repository\ConcessionRepository;
use App\Repository\ServiceHeadRepository;
use App\Repository\ServiceRepository;
use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;

/**
 * Class HeadBoardData
 * @package App\Service
 */
class HeadBoardData
{
    private $callRepository;
    private $cityRepository;
    private $concessionRepository;
    private $serviceRepository;
    private $userRepository;
    private $serviceHeadRepository;

    const IN_PROCESS     = 'in_process';
    const TO_PROCESS     = 'to_process';
    const IN_PROCESS_KEY = '-in-process';
    const TO_PROCESS_KEY = '-to-process';

    public function __construct(
        CallRepository $callRepository,
        CityRepository $cityRepository,
        ConcessionRepository $concessionRepository,
        ServiceRepository $serviceRepository,
        UserRepository $userRepository,
        ServiceHeadRepository $serviceHeadRepository
    ) {
        $this->callRepository        = $callRepository;
        $this->cityRepository        = $cityRepository;
        $this->concessionRepository  = $concessionRepository;
        $this->serviceRepository     = $serviceRepository;
        $this->userRepository        = $userRepository;
        $this->serviceHeadRepository = $serviceHeadRepository;
    }

    /**
     * @param array $data
     * $data is provided by ServiceHeadRepository->getHeadServiceCalls()
     * The array generated by this method is like below
     * $array = [
     *      cityName => [
     *              'slug'       => city-name-slug,
     *              'in_process' => int,
     *              'to_process' => int,
     *              'concessions' => [
     *                  'concessionName' => [
     *                      'slug' => concession-name-slug,
     *                      'in_process' => int,
     *                      'to_process' => int,
     *                      'services'   => [
     *                          'serviceName' => [
     *                              'slug' => service-name-slug,
     *                              'in_process'    => int,
     *                              'to_process'    => int,
     *                              'collaborators' => [
     *                                  'userFirstName userName' => [
     *                                      'user_name'  => 'userFirstName userName',
     *                                      'to_process' => int,
     *                                      'in_process' => int,
     *                                      'user_id'    => userId
     *                                  ],
     *                              ],
     *                          ],
     *                      ],
     *                  ],
     *               ],
     *          ]
     *
     * @return array
     */

    public function makeDataForHead(array $data): array
    {
        $result = [];
        $slugify = new Slugify();
        foreach ($data as $datum) {
            $serviceId     = (int)$datum['service_id'];
            $service       = $this->serviceRepository->findOneById($serviceId);
            $serviceName   = $service->getName();
            $collaborators = $service->getUsers();

            $result[$datum['city']]['slug'] = $slugify->slugify($datum['city']);
            $result[$datum['city']][self::IN_PROCESS] = (!isset($result[$datum['city']][self::IN_PROCESS]))
                ? 0 : $result[$datum['city']][self::IN_PROCESS];
            $result[$datum['city']][self::TO_PROCESS] = (!isset($result[$datum['city']][self::TO_PROCESS]))
                ? 0 : $result[$datum['city']][self::TO_PROCESS];

            $result[$datum['city']]['concessions'][$datum['concession']]['slug']
                = $slugify->slugify($datum['concession']);

            $result[$datum['city']]['concessions'][$datum['concession']][self::IN_PROCESS] =
                (!isset($result[$datum['city']]
                ['concessions'][$datum['concession']][self::IN_PROCESS])) ?
                    0 : $result[$datum['city']]['concessions']
                [$datum['concession']][self::IN_PROCESS];

            $result[$datum['city']]['concessions'][$datum['concession']][self::TO_PROCESS] =
                (!isset($result[$datum['city']]
                ['concessions'][$datum['concession']][self::TO_PROCESS])) ?
                    0 : $result[$datum['city']]['concessions']
                [$datum['concession']][self::TO_PROCESS];


            $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName] = [
                self::TO_PROCESS    => 0,
                self::IN_PROCESS    => 0,
                'collaborators' => [],
                'slug'          => $slugify->slugify($serviceName),
            ];
            foreach ($collaborators as $collaborator) {
                $collaboratorName = $collaborator->getFirstname() . ' ' . $collaborator->getLastname();
                $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName]['collaborators']
                    [$collaboratorName] =
                    [
                        'user_id'    => $collaborator->getId(),
                        'slug'       => $slugify->slugify($collaboratorName),
                        'user_name'  => $collaboratorName,
                        self::TO_PROCESS => count($this->callRepository->callsToProcessByUser($collaborator)),
                        self::IN_PROCESS => count($this->callRepository->callsInProcessByUser($collaborator)),
                    ];
                $result[$datum['city']][self::TO_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]
                ['services'][$serviceName]['collaborators'][$collaboratorName][self::TO_PROCESS];
                $result[$datum['city']][self::IN_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]
                ['services'][$serviceName]['collaborators'][$collaboratorName][self::IN_PROCESS];
                $result[$datum['city']]['concessions'][$datum['concession']][self::TO_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName]
                    ['collaborators'][$collaboratorName][self::TO_PROCESS];
                $result[$datum['city']]['concessions'][$datum['concession']][self::IN_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName]
                    ['collaborators'][$collaboratorName][self::IN_PROCESS];
                $result[$datum['city']]['concessions'][$datum['concession']]
                ['services'][$serviceName][self::TO_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName]
                    ['collaborators'][$collaboratorName][self::TO_PROCESS];
                $result[$datum['city']]['concessions'][$datum['concession']]
                ['services'][$serviceName][self::IN_PROCESS] +=
                    $result[$datum['city']]['concessions'][$datum['concession']]['services'][$serviceName]
                    ['collaborators'][$collaboratorName][self::IN_PROCESS];
            }
        }
        return $result;
    }


    public function makeDataForHeadUpdater(array $data): array
    {
        $result = [];
        $slugify = new Slugify();
        foreach ($data as $datum) {
            $serviceId     = (int)$datum['service_id'];
            $service       = $this->serviceRepository->findOneById($serviceId);
            $serviceName   = $service->getName();
            $collaborators = $service->getUsers();

            $citySlug = $slugify->slugify($datum['city']);

            $result[$citySlug . self::IN_PROCESS_KEY] = (!isset($result[$citySlug. self::IN_PROCESS_KEY]))
                ? 0 : $result[$citySlug . self::IN_PROCESS_KEY];
            $result[$citySlug . self::TO_PROCESS_KEY] = (!isset($result[$citySlug. self::TO_PROCESS_KEY]))
                ? 0 : $result[$citySlug . self::TO_PROCESS_KEY];

            $concessionSlug    = $slugify->slugify($datum['concession']);

            $result[$citySlug . '-' . $concessionSlug . self::IN_PROCESS_KEY] =
                (!isset($result[$citySlug . '-' . $concessionSlug . self::IN_PROCESS_KEY])) ?
                    0 : $result[$citySlug . '-' . $concessionSlug . self::IN_PROCESS_KEY];

            $result[$citySlug . '-' . $concessionSlug . self::TO_PROCESS_KEY] =
                (!isset($result[$citySlug . '-' . $concessionSlug . self::TO_PROCESS_KEY])) ?
                    0 : $result[$citySlug . '-' . $concessionSlug . self::TO_PROCESS_KEY];

            $serviceSlug = $slugify->slugify($serviceName);

            $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::TO_PROCESS_KEY] =
                (!isset($result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::TO_PROCESS_KEY])) ?
                    0 : $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::TO_PROCESS_KEY];
            $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::IN_PROCESS_KEY] =
                (!isset($result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::IN_PROCESS_KEY])) ?
                    0 : $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .self::IN_PROCESS_KEY];

            foreach ($collaborators as $collaborator) {
                $collSlug =
                    $slugify->slugify($collaborator->getFirstname() . ' ' . $collaborator->getLastname());
                $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug . self::TO_PROCESS_KEY]
                    = count($this->callRepository->callsToProcessByUser($collaborator));
                $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug . self::IN_PROCESS_KEY]
                    = count($this->callRepository->callsInProcessByUser($collaborator));

                $result[$citySlug . self::TO_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::TO_PROCESS_KEY];
                $result[$citySlug . self::IN_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::IN_PROCESS_KEY];
                $result[$citySlug . '-' . $concessionSlug . self::TO_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::TO_PROCESS_KEY];
                $result[$citySlug . '-' . $concessionSlug . self::IN_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::IN_PROCESS_KEY];
                $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .  self::TO_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::TO_PROCESS_KEY];
                $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug .  self::IN_PROCESS_KEY] +=
                    $result[$citySlug . '-' . $concessionSlug . '-' . $serviceSlug . '-' . $collSlug
                    . self::IN_PROCESS_KEY];
            }
        }

        return $result;
    }
}
